namespace AICompanyOS.Runtime.Memory;

/// <summary>
/// Represents the role of a participant in a conversation turn.
/// </summary>
public enum ConversationRole
{
    /// <summary>The system prompt or instruction context.</summary>
    System = 0,

    /// <summary>A message from the human/orchestrator side.</summary>
    User = 1,

    /// <summary>A message generated by the AI agent.</summary>
    Assistant = 2,

    /// <summary>The result returned by a tool call.</summary>
    Tool = 3
}

/// <summary>
/// A single turn in a conversation between the orchestrator and an AI agent.
/// Conversation turns form the message history sent to the LLM on each iteration.
/// </summary>
public sealed class ConversationTurn
{
    /// <summary>The role of the participant who produced this turn.</summary>
    public ConversationRole Role { get; init; }

    /// <summary>The text content of this turn.</summary>
    public string Content { get; init; } = string.Empty;

    /// <summary>
    /// Optional tool call ID, populated when Role is Tool
    /// to correlate the result with the originating request.
    /// </summary>
    public Guid? ToolCallId { get; init; }

    /// <summary>UTC timestamp when this turn was recorded.</summary>
    public DateTime RecordedAtUtc { get; } = DateTime.UtcNow;
}
